version: "3.7"
services:
  mongo:
    image: mongo:latest
    ports:
      - 27017:27017
  redis:
    image: redis:latest
    ports:
      - 6379:6379
  re-manager:
    build: ./re-manager
    ports:
      - 60615:60615
    volumes:
      - ${HAPPI_DB_PATH}:/happi_db.json
    depends_on:
      - "redis"
      - "zmq-proxy"
  hwproxy:
    build: ./hwproxy
    ports:
      - 60620:60620
    volumes:
      - ${HAPPI_DB_PATH}:/happi_db.json
  zmq-proxy:
    build: ./zmq-proxy
    ports:
      - 5567:5567
      - 5568:5568
  wt5:
    build: ./wt5
    depends_on:
      - "zmq-proxy"
    volumes:
      - ${WT5_DATA_PATH}:/data
x-disabled:
  bluesky-queueserver:
    build: ./bluesky-queueserver
    ports:
      - 60610:60610
    depends_on:
      - "re-manager"
  bluesky-webclient:
    image: ghcr.io/bluesky/bluesky-webclient:main
    stdin_open: true
    ports:
      - 3001:3001
    depends_on:
      - bluesky-queueserver
