FROM debian:bullseye

# python
RUN apt update
RUN apt install git -y
RUN apt install librdkafka-dev -y
RUN apt install python3-pip -y

# happi
COPY ./happi.ini /happi.ini
COPY ./requirements.txt ./
RUN pip install -r requirements.txt

ENV HAPPI_CFG /happi.ini

# re-manager
COPY ./startup.py ./startup.py
# start
CMD ["start-hwproxy-server", "--startup-script", "startup.py"]
