FROM debian:bullseye
RUN apt update
RUN apt install librdkafka-dev -y
RUN apt install python3-pip -y
RUN python3 -m pip install bluesky-queueserver
RUN python3 -c "import distutils.spawn; print(distutils.spawn.find_executable('start-re-manager'))"
CMD ["/usr/local/bin/start-re-manager"]
