name: numpy-import-test

on:
  push:

jobs:
  compose:
    runs-on: ubuntu-latest
    steps:
    - 
      name: Checkout code
      uses: actions/checkout@v5
    -
      name: Build image
      uses: docker/setup-compose-action@v2
    -
      name: Set up environment
      run: |
        cp -r ./tests/test.env .env
        echo "HAPPI_DB_PATH= $GITHUB_WORKSPACE/tests/happi_db.json" >> .env
        cp -r ./tests/numpy-test/ ./
    - 
      name: Build image
      run: docker build -t numpy-test .
    - 
      name: Run container
      run: docker run numpy-test
